---
- name: Ensure observability stack directory exists
  ansible.builtin.file:
    path: /opt/stack
    state: directory
    mode: '0755'

- name: Copy configuration files to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/stack/{{ item }}"
  with_items:
    - docker-compose.yml
    - prometheus.yml
    - traefik.yml
    - grafana-config/
  register: config_files

- name: Ensure acme.json for Let's Encrypt exists
  ansible.builtin.file:
    path: /opt/stack/acme.json
    state: touch
    mode: '0600'

- name: Deploy observability stack via Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/stack
    state: present
  environment:
    DOMAIN_NAME: "{{ domain_name }}"
  register: compose_result

- name: Debug what happened
  ansible.builtin.debug:
    var: compose_result
