---
- name: Create a directory for the observability stack
  ansible.builtin.file:
    path: /opt/stack
    state: directory
    mode: '0755'

- name: Copy configuration files to the remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/stack/{{ item }}"
  with_items:
    - docker-compose.yml
    - prometheus.yml
    - traefik.yml
    - grafana-config/
  register: config_files # Register the result to check later

- name: Create acme.json for Let's Encrypt certificates
  ansible.builtin.file:
    path: /opt/stack/acme.json
    state: touch
    mode: '0600'

- name: Tear down any existing containers if config changed
  ansible.builtin.command:
    cmd: docker compose down
    chdir: /opt/stack
  environment:
    DOMAIN_NAME: "{{ domain_name }}"
  when: config_files.changed

- name: Launch or update the observability stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/stack
  environment:
    DOMAIN_NAME: "{{ domain_name }}"
  when: config_files.changed