---
- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to docker group
  ansible.builtin.user:
    name: "{{ remote_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection to apply group changes
  ansible.builtin.meta: reset_connection

- name: Ensure prerequisites are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Ensure Docker GPG key is present
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Ensure Docker APT repo is configured
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Ensure Docker packages are installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Make sure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
