---
- name: Update apt cache if older than 1 hour
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Time in seconds

- name: Upgrade all apt packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes # Use apt-get instead of apt to avoid some interactive prompts

- name: Install prerequisites for Docker repository
  ansible.builtin.apt:
    name: ['ca-certificates', 'curl', 'gnupg']
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine and plugins
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
    state: present
    update_cache: yes