---
- name: Configure and Deploy Observability Stack
  hosts: servers
  become: true # Use become at the top level to apply sudo to roles

  vars:
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"

  roles:
    - role: docker
    - role: observability_stack