---
- name: Configure and Deploy Observability Stack
  hosts: servers
  tasks:
    - name: Update all apt packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install prerequisites for Docker repository
      ansible.builtin.apt:
        name: ['ca-certificates', 'curl', 'gnupg']
        state: present

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker Engine and plugins
      ansible.builtin.apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
        state: present
        update_cache: yes

    - name: Create a directory for the observability stack
      ansible.builtin.file:
        path: /opt/stack
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml to the remote host
      ansible.builtin.copy:
        src: files/docker-compose.yml
        dest: /opt/stack/docker-compose.yml

    - name: Copy prometheus.yml to the remote host
      ansible.builtin.copy:
        src: files/prometheus.yml
        dest: /opt/stack/prometheus.yml

    - name: Tear down any existing containers
      ansible.builtin.command:
        cmd: docker compose down
        chdir: /opt/stack

    - name: Launch the observability stack with Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/stack