---
observability_config:
  acme_email: "letsencrypt@trelvik.net"
  
  base_directory: /opt/stack
  
  # Static files to be copied
  files:
    - name: docker-compose.yml
      mode: '0644'
    - name: prometheus.yml
      mode: '0644'

  # Templated files to be processed
  templated_files:
    - name: traefik.yml
      dest_name: traefik.yml # The final name on the server
      src_name: traefik.yml.j2 # The source template name
      mode: '0644'
    - name: grafana.ini
      dest_name: grafana.ini
      src_name: grafana.ini.j2
      mode: '0644'
  
  # Directories to copy
  directories:
    - name: grafana-config
      src: grafana-config/
      dest: grafana-config/
      file_mode: '0644'
      dir_mode: '0755'
    - name: promtail-config
      src: promtail-config/  
      dest: promtail-config/
      file_mode: '0644'
      dir_mode: '0755'
  
  # Special files with custom permissions
  special_files:
    - path: acme.json
      mode: '0600'
      owner: root
      group: root
      state: touch
